const tabelafilmes = [
  {
    id: 1,
    nome: "O Poderoso Chefão",
    sigla: "OPC",
    ano: 1972,
    diretor: "Francis Ford Coppola",
    genero: "Drama",
    duracao: 175,
    avaliacao: 9.2,
    oscars: 3,
    bilheteria: 250000000,
  },
  {
    id: 2,
    nome: "O Senhor dos Anéis: O Retorno do Rei",
    sigla: "OSDAR",
    ano: 2003,
    diretor: "Peter Jackson",
    genero: "Fantasia",
    duracao: 201,
    avaliacao: 8.9,
    oscars: 11,
    bilheteria: 1150000000,
  },
  {
    id: 3,
    nome: "Interestelar",
    sigla: "INT",
    ano: 2014,
    diretor: "Christopher Nolan",
    genero: "Ficção Científica",
    duracao: 169,
    avaliacao: 8.6,
    oscars: 1,
    bilheteria: 700000000,
  },
  {
    id: 4,
    nome: "Coringa",
    sigla: "COR",
    ano: 2019,
    diretor: "Todd Phillips",
    genero: "Suspense",
    duracao: 122,
    avaliacao: 8.4,
    oscars: 2,
    bilheteria: 1070000000,
  },
  {
    id: 5,
    nome: "Kill Bill: Volume 1",
    sigla: "KBV1",
    ano: 2003,
    diretor: "Quentin Tarantino",
    genero: "Ação",
    duracao: 111,
    avaliacao: 8.1,
    oscars: 0,
    bilheteria: 180000000,
  },
  {
    id: 6,
    nome: "Titanic",
    sigla: "TIT",
    ano: 1997,
    diretor: "James Cameron",
    genero: "Romance",
    duracao: 194,
    avaliacao: 7.9,
    oscars: 11,
    bilheteria: 2260000000,
  },
  {
    id: 7,
    nome: "Matrix",
    sigla: "MAT",
    ano: 1999,
    diretor: "Lana Wachowski e Lilly Wachowski",
    genero: "Ficção Científica",
    duracao: 136,
    avaliacao: 8.7,
    oscars: 4,
    bilheteria: 467000000,
  },
  {
    id: 8,
    nome: "Gladiador",
    sigla: "GLA",
    ano: 2000,
    diretor: "Ridley Scott",
    genero: "Ação",
    duracao: 155,
    avaliacao: 8.5,
    oscars: 5,
    bilheteria: 465000000,
  },
  {
    id: 9,
    nome: "Forrest Gump",
    sigla: "FOR",
    ano: 1994,
    diretor: "Robert Zemeckis",
    genero: "Drama",
    duracao: 142,
    avaliacao: 8.8,
    oscars: 6,
    bilheteria: 678000000,
  },
  {
    id: 10,
    nome: "Jurassic Park",
    sigla: "JUR",
    ano: 1993,
    diretor: "Steven Spielberg",
    genero: "Aventura",
    duracao: 127,
    avaliacao: 8.2,
    oscars: 3,
    bilheteria: 1090000000,
  },
];

export default tabelafilmes;
